#!/usr/bin/kivy
'''
[ MODE ENCODE ]
Dictionary to manage all values
'''

o_o = {
    'rls_source': '',
    'rls_title': '',
    'resolution': [],
    'crop_width': '',
    'crop_height': '',
    'crop_top': '',
    'crop_bottom': '',
    'crop_right': '',
    'crop_left': '',
    'deinterlace': '',
    'motion_deint': '',
    'denoise': '',
    'decimate': '',
    'video_ID': '',
    'movie_name': '',
    'container': '',
    'video_codec': '',
    'crf_mode': '',
    'dual_pass': '',
    'fast1pass': '',
    'framerate': '',
    'preset': '',
    'tune': '',
    'profile': '',
    'level': '',
    'audio_ID': [],
    'audio_title': [],
    'audio_lang': [],
    'audio_codec': [],
    'audio_bitrate': [],
    'audio_channels': [],
    'audio_samplerate': [],
    'audio_gain': [],
    'subs_ID': [],
    'subs_source': [],
    'subs_codec': [],
    'subs_lang': [],
    'subs_forced': [],
    'subs_burned': [],
    'subs_charset': [],
    'max_Bframes': '',
    'ref_frames': '',
    'threads_mod': '',
    'threads_nb': '',
    'mixed_ref': '',
    'B_frames': '',
    'me_range': '',
    'distord_rate': '',
    'key_interv': '',
    'fast_skip': '',
    'grayscale': '',
    'min_key': '',
    'lookahead': '',
    'bluray': '',
    'scenecut': '',
    'chroma': '',
    'deblock_beta': '',
    'deblock_alpha': '',
    'psy_trellis': '',
    'partitions': '',
    'weighted_bf': '',
    'pyramid_mod': '',
    'transform': '',
    'weighted_pf': '',
    'trellis': '',
    'adapt_strenght': '',
    'me_method': '',
    'cabac': '',
    'direct_mod': '',
    'subpixel': '',
    'psy_optim': ''}
