#:kivy 1.8.0

# ---------- EXIT POPUP ----------
<ExitPopup>:
    size_hint: .3, .2
    auto_dismiss: False
    title: 'Exit'

    GridLayout:
        size_hint: 1, 1
        orientation: 'vertical'
        cols: 1

        # --- Confirm ---
        Button:
            text: 'Confirm'
            on_press: exit()

        # --- Cancel ---
        Button:
            text: 'Cancel'
            on_press: root.dismiss()
